services:
  Draw\Swagger\Extraction\Extractor\DoctrineInheritanceExtractor:
    class: 'Draw\Swagger\Extraction\Extractor\DoctrineInheritanceExtractor'
    arguments:
      - '@doctrine'
    tags:
      - name: 'swagger.extractor'

  Draw\SwaggerBundle\Extractor\JmsSerializer\ReferenceTypeToSchemaHandler:
    class: 'Draw\SwaggerBundle\Extractor\JmsSerializer\ReferenceTypeToSchemaHandler'
    arguments:
      - '@doctrine'

  Draw\SwaggerBundle\Listener\ObjectReferenceSerializer:
    class: 'Draw\SwaggerBundle\Listener\ObjectReferenceSerializer'
    arguments:
      - '@doctrine'
    tags:
      - name: 'jms_serializer.subscribing_handler'