parameters:
    draw.swagger.extractor.fos_rest_view_operation_extractor.class: Draw\SwaggerBundle\Extractor\FOSRestViewOperationExtractor
    draw.swagger.extractor.fos_rest_route_operation_extractor.class: Draw\SwaggerBundle\Extractor\FOSRestRouteOperationExtractor

services:
    draw.swagger.extractor.fos_rest_view_operation_extractor:
        class: '%draw.swagger.extractor.fos_rest_view_operation_extractor.class%'
        arguments:
            - '@annotation_reader'
        tags:
            - {name: swagger.extractor}

    draw.swagger.extractor.fos_rest_route_operation_extractor:
        class: '%draw.swagger.extractor.fos_rest_route_operation_extractor.class%'
        arguments:
            - '@fos_rest.request.param_fetcher.reader'
        tags:
            - {name: swagger.extractor}