parameters:
    draw.swagger.class: Draw\Swagger\Swagger
    draw.swagger.extractor.php_doc_operation_exractor.class: Draw\Swagger\Extraction\Extractor\PhpDocOperationExtractor
    draw.swagger.extractor.jms_extractor.class: Draw\Swagger\Extraction\Extractor\JmsExtractor
    draw.swagger.extractor.symfony_container_swagger_extractor.class: Draw\SwaggerBundle\Extractor\SymfonyContainerSwaggerExtractor
    draw.swagger.extractor.route_operation_extractor.class: Draw\SwaggerBundle\Extractor\RouteOperationExtractor
    draw.swagger.extractor.swagger_schema_extractor.class: Draw\Swagger\Extraction\Extractor\SwaggerSchemaExtractor
    draw.swagger.extractor.param_converter_extractor.class: Draw\SwaggerBundle\Extractor\ParamConverterExtractor
    draw.swagger.extractor.type_schema_extractor.class: Draw\Swagger\Extraction\Extractor\TypeSchemaExtractor

services:
    Draw\Swagger\JMSSerializerHandler:
        class: 'Draw\Swagger\JMSSerializerHandler'
        autoconfigure: true
        autowire: true

    Draw\Swagger\JMSSerializerListener:
        class: 'Draw\Swagger\JMSSerializerListener'
        autoconfigure: true
        autowire: true

    Draw\Swagger\Swagger:
        class: '%draw.swagger.class%'
        arguments:
            - '@jms_serializer.serializer'
        public: true

    draw.swagger:
        alias: 'Draw\Swagger\Swagger'
        public: true

    draw.swagger.extractor.symfony_container_swagger_extractor:
        class: '%draw.swagger.extractor.symfony_container_swagger_extractor.class%'
        arguments:
            - '@annotation_reader'
        tags:
            - {name: swagger.extractor}

    draw.swagger.extractor.swagger_tag_extractor:
        class: Draw\Swagger\Extraction\Extractor\SwaggerTagExtractor
        arguments:
            - '@annotation_reader'
        tags:
            - {name: swagger.extractor}

    draw.swagger.extractor.swagger_schema_extractor:
        class: '%draw.swagger.extractor.swagger_schema_extractor.class%'
        arguments:
            - '@jms_serializer.serializer'
        tags:
            - {name: swagger.extractor}

    draw.swagger.extractor.type_schema_extractor:
        class: '%draw.swagger.extractor.type_schema_extractor.class%'
        tags:
            - {name: swagger.extractor}

    draw.swagger.extractor.route_operation_extractor:
        class: '%draw.swagger.extractor.route_operation_extractor.class%'
        tags:
            - {name: swagger.extractor}

    Draw\SwaggerBundle\Extractor\ViewExtractor:
        class: "Draw\\SwaggerBundle\\Extractor\\ViewExtractor"
        tags:
            - {name: swagger.extractor}
        autoconfigure: true
        autowire: true

    draw.swagger.extractor.jms_extractor:
        class: '%draw.swagger.extractor.jms_extractor.class%'
        arguments:
            - '@jms_serializer.metadata_factory'
            - '@jms_serializer.naming_strategy'
        tags:
            - {name: swagger.extractor}

    draw.swagger.jms_serializer_listener:
        class: Draw\Swagger\JMSSerializerListener
        tags:
            - {name: jms_serializer.event_subscriber}

    draw.swagger.extractor.constraint_extractor:
        abstract: true
        calls:
            - [setMetadataFactory, ['@validator.mapping.class_metadata_factory']]

    draw.swagger.extractor.constraint_extractor.not_null:
        parent: draw.swagger.extractor.constraint_extractor
        class: Draw\Swagger\Extraction\Extractor\Constraint\NotNullConstraintExtractor

    draw.swagger.extractor.constraint_extractor.choice:
        parent: draw.swagger.extractor.constraint_extractor
        class: Draw\Swagger\Extraction\Extractor\Constraint\ChoiceConstraintExtractor

    draw.swagger.extractor.constraint_extractor.not_blank:
        parent: draw.swagger.extractor.constraint_extractor
        class: Draw\Swagger\Extraction\Extractor\Constraint\NotBlankConstraintExtractor

    draw.swagger.extractor.constraint_extractor.range:
        parent: draw.swagger.extractor.constraint_extractor
        class: Draw\Swagger\Extraction\Extractor\Constraint\RangeConstraintExtractor

    draw.swagger.extractor.constraint_extractor.length:
        parent: draw.swagger.extractor.constraint_extractor
        class: Draw\Swagger\Extraction\Extractor\Constraint\LengthConstraintExtractor

    draw.swagger.extractor.constraint_extractor.count:
        parent: draw.swagger.extractor.constraint_extractor
        class: Draw\Swagger\Extraction\Extractor\Constraint\CountConstraintExtractor

    draw.swagger.extractor.php_doc_operation_exractor:
        class: '%draw.swagger.extractor.php_doc_operation_exractor.class%'
        tags:
            - {name: swagger.extractor}

    draw.swagger.extractor.param_converter_extractor:
        class: '%draw.swagger.extractor.param_converter_extractor.class%'
        arguments:
            - '@annotations.reader'
        tags:
            - {name: swagger.extractor}
